name: pr-validation

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.13','1.14','1.15','1.16','1.17']
        sqlImage: ['2017-latest','2019-latest']
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '${{ matrix.go }}'
    - name: Run tests against Linux SQL
      run: |
        go version
        go get -d
        go build
        export SQLCMDPASSWORD=$(date +%s|sha256sum|base64|head -c 32)
        export SQLCMDUSER=sa
        export SQLUSER=sa
        export SQLPASSWORD=$SQLCMDPASSWORD
        export DATABASE=test
        docker run -m 2GB -e ACCEPT_EULA=1 -d --name sql2017 -p:1433:1433 -e SA_PASSWORD=$SQLCMDPASSWORD mcr.microsoft.com/mssql/server:${{ matrix.sqlImage }}
        wget  https://github.com/microsoft/go-sqlcmd/releases/download/v0.5.0/sqlcmd-v0.5.0-linux-x64.tar.bz2 -O sqlcmd.tar.bz2
        tar -xvf sqlcmd.tar.bz2
        sqlcmd -Q "CREATE DATABASE test"
        go test -race -cpu 4 ./...
